# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='pictureurl',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
        migrations.AddField(
            model_name='category',
            name='andurl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='cats',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='introduction',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='iosurl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='pcurl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='releasedate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='yturl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='message',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(default='', upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='review',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
