# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20190312_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='pictureurl',
        ),
        migrations.RemoveField(
            model_name='page',
            name='review',
        ),
        migrations.AddField(
            model_name='category',
            name='pictureurl',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='review',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
