# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-12 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_page_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='picture',
        ),
    ]
